### ISSUE TITLE
separate sound controls for correct and incorrect inputs

### ISSUE THREAD

**Issue by thatsweetdoja** [ranelpadon/ngram-type#14] opened 2022-03-25 20:06 UTC
The delay on the typewriter noise makes it hard to keep a consistent rhythm, but I would still like to be able to tell when I miss a letter without looking at the screen

**Comment by ranelpadon** [comment] 2022-03-27 04:04
@thatsweetdoja Thanks for your feedback. It has 4 sounds actually:

**Typing** sound:
- correct letter
- incorrect letter

**Result** sound (if within the WPM/Accuracy threshold)
- pass 
- fail 

Are you suggesting to have controls for these 4 sounds (i.e. 4 controls), to have controls for the **Typing** and **Result** sounds (i.e. 2 controls), or to have controls for the correct letter/pass result and incorrect letter/fail result (i.e. 2 controls)?

**Comment by ranelpadon** [comment] 2022-03-27 15:29
@thatsweetdoja I implemented the 4 granular sound controls, plus other style improvements. Working as intended in my preliminary testing. Let me know what you think:

<img width="1440" alt="Screen Shot 2022-03-27 at 11 26 28 PM" src="https://user-images.githubusercontent.com/4292088/160288758-6c7509a5-89dd-4748-9cf7-27b4cac91137.png">

Thanks

**Comment by thatsweetdoja** [comment] 2022-03-27 17:57
This is awesome, exactly what I had in mind! I don't think it's too bad in terms of UI impact, but one thing that might clean it up a little is moving the switches into a collapsible card. I did a real quick and dirty mockup based on the bootstrap docs as an example. https://pastebin.com/sSH0XVWW
![card closed](https://user-images.githubusercontent.com/98777717/160293993-191fae42-63bd-4067-9e51-c191babe7703.png)
![card open](https://user-images.githubusercontent.com/98777717/160293994-cbafbe75-6115-494b-831e-eaa92d08b8d7.png)

**Comment by ranelpadon** [comment] 2022-03-27 19:18
Right, that's a good idea to reduce clutter! I'll add it asap. At least it's functional now and just needs some UI enhancements. Thanks!

**Comment by thatsweetdoja** [comment] 2022-03-27 20:50
Happy to help, this is a super helpful tool!

**Comment by ranelpadon** [comment] 2022-03-28 06:49
@thatsweetdoja I implemented the collapsible sounds section now. Didn't know that Bootstrap has an easy mechanism for collapsing, which is kinda similar to modal windows. So, the `Sounds` text/button is now the trigger for collapsing the section below it. I decided to use color to convey that it's clickable for simplicity and consistency with the `Custom` modal window/link for custom data set:

<img width="1440" alt="Screen Shot 2022-03-28 at 2 42 33 PM" src="https://user-images.githubusercontent.com/4292088/160341398-cb9f04fe-7f75-4888-9cd6-0e123f57d79c.png">

Please check once you have the chance. Thanks :)

**Comment by thatsweetdoja** [comment] 2022-03-29 19:41
Looks great!

**Comment by ranelpadon** [comment] 2022-04-01 05:08
Closing this issue/suggestion since it's working as intended now. Thanks again for your feedback. :)

**Closed by ranelpadon** 2022-04-01 05:08 UTC
